### ISSUE TITLE
Question: Support for Material 3?

### ISSUE THREAD

**Issue by lnaie** [anfeichtinger/flutter_production_boilerplate_riverpod#4]
Hello,

I'm new to the coding side, although I follow the news.
I did see this setting ```uses-material-design: false```, but I thought I should ask anyway.

Any plans to support the Material 3, just advertised at google io 2023?

Thanks

**Comment by reafeichtinger** [comment]
Currently the boilerplate includes a custom theme that does not require `use-material-design: true`. The setting was mainly set to `false` to save some space in the final application because e.g. the material icons font will not be included.

In order to support Material 3 I'm not sure if it is necessary to enable this flag. More important will be setting the `useMaterial3` setting in your `ThemeData`. For more info you can read through some of the stuff here: [https://m3.material.io/develop/flutter](https://m3.material.io/develop/flutter)

Since I'm not actively following Flutter development at the moment I cannot promise to include Material 3 in this project or that it will be always up-to-date. When I can find the time I update the code and try to use the latest best-practices.
